instances:
  
  postgres:
    build:
      context: ./odc/postgres
      recipe: postgres.def
    ports:
      - 5432:5432
    volumes:
      - ./odc/postgres/env_postgres.sh:/.singularity.d/env/env_postgres.sh
  
  jupyter:
    build:
      context: ./odc/jupyter
      recipe: jupyter.def
    ports:
      - 8888:8888
    volumes:
      - ./odc/jupyter/env_jupyter.sh:/.singularity.d/env/env_jupyter.sh
      #- ./odc/jupyter/notebooks:/opt/notebooks
      - /home/marco/pypypy/ARDCube/notebooks:/opt/notebooks
    command: ["/bin/tini", "-s", "--", "jupyter", "notebook", "--notebook-dir=/opt/notebooks", "--ip='0.0.0.0'", "--port=8888", "--no-browser", "--allow-root"]

  force:
    build:
      context: ./force
      recipe: force.def

  pyrosar:
    build:
      context: ./pyrosar
      recipe: pyrosar.def
