# https://github.com/opendatacube/cube-in-a-box

version: "1.0"

instances:

  postgres:
    build:
      context: ./odc/postgres
      recipe: postgres.def
    ports:
      - 5432:5432
    volumes:
     - ./odc/postgres/env_postgres.sh:/.singularity.d/env/env_postgres.sh
  
  jupyter:
    build:
      context: ./odc/jupyter
      recipe: jupyter.def
    ports:
      - 8888:8888
    volumes:
      - ./odc/jupyter/env_jupyter.sh:/.singularity.d/env/env_jupyter.sh
      - /home/marco/pypypy/ARDCube/notebooks:/opt/notebooks