## https://github.com/opendatacube/cube-in-a-box

version: "1.0"

instances:

  odc-postgres:
    build:
      context: ./postgres
      recipe: postgres.def
    ports:
      - 5432:5432
    volumes:
     - ./postgres/env_file.sh:/.singularity.d/env/env_file.sh
  
  odc-jupyter:
    build:
      context: ./jupyter
      recipe: jupyter.def
    volumes:
      - ./jupyter/env_file.sh:/.singularity.d/env/env_file.sh
      - /home/marco/pypypy/ARDCube/notebooks:/opt/notebooks
    ports:
      - 80:8888
    command: jupyter notebook --allow-root --ip="0.0.0.0" --NotebookApp.token='secretpassword'